// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ktwzuaqoezafztvinzjm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt0d3p1YXFvZXphZnp0dmluemptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc2MjYxOTksImV4cCI6MjA1MzIwMjE5OX0.vRPZYLj8p_XqYkWzIGVBfE82fbFcFTUr12ObkSDaMl0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);